### ISSUE TITLE
Profile command question

### ISSUE THREAD

**Issue by The1stMartian** [menzel/nopeak#6]
Hi, I'm having some trouble using the PROFILE command. I'm mapping single end reads to the D. melanogaster genome, following the steps in your tutorial more or less exactly. The sam/bam/bed files looks just fine and there are about 11M mapped reads. I'm issuing the following command within the docker container:

    root@692acae6ae87:/home/nl# java -jar /usr/local/lib/noPeak.jar PROFILE --reads /home/nl/r1Rep1.bed --genome /home/nl/dm6.fasta -k 20
    [92] Building profiles for 20-mers for a radius of 500 bp around each read
    Reading reads from file /home/nl/r1Rep1.bed
    0 of 1 tasks are finished.
    Folding and mergin profile (Single threaded)
    Wrote profiles to /home/nl/profile_r1Rep1.bed.csv
	
Unfortunately, profile_r1Rep1.bed.csv has only 7 lines:

    # genome: dm6.fasta
    # reads: r1Rep1.bed
    # radius: 500
    # q: 20
    # reads used: 0
    "qmer	1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	"...
    "1000	1001	"

If I use this file as input for the LOGO command, it results in an error: "No valid profiles found."

Grateful for any suggestions!

- CB

**Comment by menzel** [comment]
Hello,

yes, there are no profiles generated. Could you try the command again with a smaller k size? Maybe try the default 8.
Because 20-mers are quite rare, leading to very few reads of the 11M are being mapped near one. Of my head I cannot remember, but I assume there is some kind of filter for profiles with less than X reads.

If you are interested in longer k-mers you could try to combine them afterwards by overlapping fractions.

If none of this helps you can upload the .bed and genome somewhere and give me the link (somewhere private) and I'll give it a try.
